export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const REQUEST_ETHEREUM_CHALLENGE = 'REQUEST_ETHEREUM_CHALLENGE';
export const SUBMIT_ETHEREUM_CHALLENGE = 'SUBMIT_ETHEREUM_CHALLENGE';

export const USER_INFO = 'USER_INFO';
export const SET_WEB3_ACCOUNT = 'SET_WEB3_ACCOUNT';


